spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/board-db
    username: sai4875
    password: 626512

  security:
    user:
      name: board-admin
      password: board-admin-password

logging:
  level:
    root: INFO




